config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, presence: true, 
		length: {minimum: 5, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true,
		length: {minimum: 5, maximum: 50},
		format: {with: VALID_EMAIL_REGEX}
	has_many :articles
	has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			flash[:notice] = "Article was created successfully"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def index 
		@articles = Article.all
	end

	def edit
		@article = Article.find(params[:id])
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:notice] = "Article deleted"
		redirect_to articles_path
	end
	def update 
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:notice] = "Article updated successfully"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end
	private
		def article_params
			params.require(:article).permit(:title, :description)
		end
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
	def about

	end
	def home

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Welcome to alpha blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def index 
		@user = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:notice] = "User deleted"
		redirect_to articles_path
	end
	def update 
		@user = User.find(params[:id])
		if @user.update (user_params)
			flash[:success] = "User updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end
	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options={size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt:user.username, class: "img-circle")
	end	
end

app/views/articles/_article.html.erb
<% obj.each do |a| %>
	<div class="row">
		<div class="col-md-8 col-sm-offset-2">
			<div class="well">
				<div class="article-title">
					<%= link_to a.title, article_path(a) %>
				</div>
				<div class="article-body">
					<%= truncate(a.description, length: 100) %>
					<div class="article-meta-details">
						<small>Created by: <%= a.user.username %></small>
						<%= time_ago_in_words(a.created_at) %> ago
						<%= time_ago_in_words(a.updated_at) %> ago
					</div>
				</div>
				<div class="article-actions">
					<%= link_to "Edit this article", edit_article_path(a), class:"btn btn-sm btn-primary" %>
					<%= link_to "Delete this artcle", article_path(a), method: :delete, data: {confirm: "Are you sure ypu want to delete?"}, class: "btn btn-sm btn-primary" %>
				</div>
			</div>
		</div>
	</div>

<%end%>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
	<h3> The following erros occured</h3>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
		<% end %>
	</ul>
<% end %>
<div class="row">
	<div class="col-md-12">	
	
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-md-2">			
					<%= f.label :title %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of the articke", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :description %>
				</div>
				<div class="col-md-8">
					<%= f.text_area :description, class: "form-control", placeholder: "Body of the article" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<%= f.submit class: "btn btn-primary btn-md" %>
				</div>
			</div>
	</div>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<%= render 'article', obj: @articles %>

<br>

<%= link_to 'Create new article', new_article_path %>

app/views/articles/new.html.erb
<h1>create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>

<%= link_to 'Edit article', edit_article_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">  <!-- to full width -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>	
			</button>
			<%= link_to 'Alpha-blog', root_path, class: 'navbar-brand', id: 'logo' %>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to "Articles", articles_path %></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Actions <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li> <%= link_to "New Article", new_article_path %></li>
					</ul>
				</li>
			</ul>			
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<% flash.each do |name,msg| %>
		<UL>
			<li> <%= msg %> </li>
		</UL>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<h1>Welcome Home</h1>

app/views/users/_form.html.erb
<div class="row">
	<div class="col-md-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :username %>
				</div>
				<div class="col-md-8">
					<%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :email %>
				</div>
				<div class="col-md-8">
					<%= f.text_area :email, class: "form-control", placeholder: "Enter your email" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-md-2">
					<%= f.label :password %>
				</div>
				<div class="col-md-8">
					<%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-md")%>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All user</h1>


<table border="1" style="text-align: center;">
	
		<tr>
			<th>id</th>
			<th>username</th>
			<th>email</th>
			<th>description</th>
			<th>created date</th>
			<th>updated date</th>
			<th>helper</th>
			<th>helper</th>
		</tr>

		<% @user.each do |u| %>
			<tr>
				<td>
					<%= u.id %>
				</td>
				<td>
					<%= link_to u.username, user_path(u.id) %>
				</td>
				<td>
					<%= u.description %>
				</td>
				<td> 
					<%= time_ago_in_words(u.created_at) %> 
				</td>
				<td>
					<%= time_ago_in_words(u.updated_at) %>
				</td>
				<td>
					<%= link_to 'Edit', edit_user_path(u.id) %>
				</td>
				<td>
					<%= link_to 'Delete', user_path(u), method: :delete %>
				</td>
			</tr>
		<% end %>
</table>

<br>

<%= link_to 'Create new user', signup_path %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>